odom_frame: odom
base_link_frame: base_link
map_frame: map
world_frame: map

two_d_mode: true

frequency: 100

odom0: /roboteq/odom
odom0_config: [false, false, false,
               false, false, false,
               true, true, false,
               false, false, true,
               false, false, false]
odom0_differential: false
odom0_queue_size: 10

odom1: /odometry/rover_gps
odom1_config: [true, true, false,
               false, false, false,
               false, false, false,
               false, false, false,
               false, false, false]
odom1_differential: false
odom1_queue_size: 10

imu0: /imu
imu0_config: [false, false, false,
              false, false, false,
              false, false, false,
              false, false, true,
              true, false, false]
imu0_differential: false
imu0_queue_size: 10
imu0_remove_gravitational_acceleration: true

# imu0: navsat/heading/
# imu0_config: [false, false, false,
#               false, false, true,
#               false, false, false,
#               false, false, false,
#               false, false, false]
# imu0_differential: false
# imu0_queue_size: 10

