#Travix CI Config based on industrial_ci(https://github.com/ros-industrial/industrial_ci.git).

sudo: required
language: generic

cache:
  directories:
    - $HOME/.ccache

# configure the build environment(s)
# https://github.com/ros-industrial/industrial_ci/blob/master/doc/index.rst#variables-you-can-configure
env:
  global: # global settings for all jobs
    # Use StereoLabs' Docker img for CUDA and ZED SDK
    - DOCKER_BASE_IMAGE="stereolabs/zed:ubuntu1604-cuda9.0-zed2.6"

    - CCACHE_DIR=$HOME/.ccache # enables C/C++ caching in industrial_ci

    # Install dependencies that can't be resolved by rosdep
    - UPSTREAM_WORKSPACE="file"
    - ROSINSTALL_FILENAME="uwrt_rover.rosinstall"
    
    - BEFORE_SCRIPT='ln -sf $(pwd)/Workspace/src/* $CATKIN_WORKSPACE/src && rm $CATKIN_WORKSPACE/src/MarsRover2019'

  matrix: # each line is a job
    - ROS_DISTRO="kinetic" ROS_REPO="ros"

    # Job to check if new release of dependent package breaks build
    - ROS_DISTRO="kinetic" ROS_REPO="ros-shadow-fixed" 

# clone and run industrial_ci
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .industrial_ci_config

script:
  - .industrial_ci_config/travis.sh
