######################
##    CAN Config    ##
######################

# Interface
can_device: "can0"
receiver_interface:    "can0"
transmitter_interface: "can0"

#fiter for acceptable ids 
can_ids: [301, 302, 303]
# Topics
# in ROS, dictionaries must have string keys
ids_to_topics: {"0x500": "/can/arm_joints/turntable",
                "0x501": "/can/arm_joints/shoulder",
                "0x502": "/can/arm_joints/elbow",
                "0x503": "/can/arm_joints/wristpitch",
                "0x504": "/can/arm_joints/wristroll",
                "0x505": "/can/arm_joints/claw"}

#can_ids:          {"301": "shoulderEncoder",
#                         "302": "elbowEncoder",
#                         "303": "wristPitchEncoder"}
#output_topics:         ["/encoders"]
